title:            Justin Higgins - @(h|j|jh)iggins
url:              http://encapsulate.me
permalink:        pretty
pygments:         true
markdown:         rdiscount
rdiscount:
  extensions:     [smart]
google_analytics: UA-48567204-1
timezone:         Pacific/San Francisco
paginate: 5
links:
  - name:         About
    url:          /whois
  - name:         Input
    url:          /i
  - name:         Output
    url:          /o
  - name:         Next
    url:          /next