#! /Users/justin/.nvm/versions/node/v16.18.0/bin/node

// PURPOSE:
// Keep a daily streak on leetcode so you stay sharp

// NOTE: globally installed
const fetch = require("isomorphic-fetch");

(async () => {
  try {
    console.log("\033[95mChecking Leetcode streak info...\033[0m")
    const resp = await fetch("https://leetcode.com/graphql/", {
      "headers": {
          "content-type": "application/json",
      },
      "body": "{\"query\":\"\\n    query userProfileCalendar($username: String!, $year: Int) {\\n  matchedUser(username: $username) {\\n    userCalendar(year: $year) {\\n      activeYears\\n      streak\\n      totalActiveDays\\n      dccBadges {\\n        timestamp\\n        badge {\\n          name\\n          icon\\n        }\\n      }\\n      submissionCalendar\\n    }\\n  }\\n}\\n    \",\"variables\":{\"username\":\"justinhiggins\"}}",
      "method": "POST"
    });
    const { data } = await resp.json();
    const now = new Date();
    now.setUTCHours(0,0,0,0);
    const today = now.getTime() / 1000;
    const submissions = JSON.parse(data.matchedUser.userCalendar.submissionCalendar);
    if (submissions.hasOwnProperty(today)) {
      console.log("\033[92mLeetcode streak extended today!\033[0m")
    } else {
      console.log("\033[91mLeetcode streak NOT extended today! Rejecting push\033[0m");
      process.exit(1)
    }
  } catch(e) {
    console.error("Error: ", e);
    console.log("\033[91mError checking leetcode! Rejecting push\033[0m");
    process.exit(1);
  }
})();
