on: [push]

jobs:
  publish_blog_to_hn:
    runs-on: ubuntu-latest
    name: Post to Hackernews
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install workflow dependencies
        run: npm install
      - id: files
        uses: jitterbit/get-changed-files@v1
      - id: posts
        name: Detecting posts from newly added files
        run: |
          i=0
          for added_file in ${{ steps.files.outputs.added }}; do
            echo "Do something with ${added_file}."
            if [[ "${added_file}" == "testing"* ]];
            then
              echo "File ${added_file} matched post."
              echo "::set-output name=post${i}::${added_file}"
              ((i=i+1))
            fi
          done

      - if: steps.posts.outputs.post0
        id: extract_title
        name: Extract title from HTML source
        uses: ./.github/actions/extractHTMLTitle/
        with:
          ADDED_FILE_NAME: steps.posts.outputs.post0
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}